### ISSUE TITLE
This is related to npm not being able to find a file

### ISSUE THREAD

**Issue by Jesus-QC** [MatteZ02/discord-interactions#10]
![image](https://user-images.githubusercontent.com/69375249/104639623-ecf5f000-56a7-11eb-8c6e-6e93058f84cf.png)

**Comment by Nicholaiii** [comment]
You must `npm i discord-slash-commands-client`

**Comment by Jesus-QC** [comment]
No, i mean 
![image](https://user-images.githubusercontent.com/69375249/104767210-0fe9d800-576c-11eb-99ce-6a2fc46bccd3.png)

**Comment by Jesus-QC** [comment]
i mean 
![image](https://user-images.githubusercontent.com/69375249/104767345-3f98e000-576c-11eb-9be8-a61967f8d6d3.png)

And what does this mean 
![image](https://user-images.githubusercontent.com/69375249/104767366-4aec0b80-576c-11eb-9ca2-2ddfaa70ab12.png)

**Comment by joelnedev** [comment]
> i mean
> ![image](https://user-images.githubusercontent.com/69375249/104767345-3f98e000-576c-11eb-9be8-a61967f8d6d3.png)
> 
> And what does this mean
> ![image](https://user-images.githubusercontent.com/69375249/104767366-4aec0b80-576c-11eb-9ca2-2ddfaa70ab12.png)

as for the error i'm not sure, but if you copied the skeleton code from the readme into your index, then on your ready event it creates the command "ping" with description "ping pong" and logs it to the console if successful.

**Comment by MatteZ02** [comment]
The error is that you haven't installed git.
