### ISSUE TITLE
Add support for commonjs and es modules

### ISSUE THREAD

**Issue by joelnedev** [MatteZ02/discord-interactions#19]
A good number of users still using the old commonjs system (node require) have come to the Discord server and this repo, not knowing why the module isn't working for them. It should include support for CJS and ESM so it can be used without replacing every require call with an import statement (possibly similar to how d.js does it).

**Comment by lhjt** [comment]
Yes unfortunately I forgot to include cjs support in the PR to implement TS (#17), and so I've opened a PR to add it now.

**Comment by MatteZ02** [comment]
This was fixed by #20
