### ISSUE TITLE
Can only create 5 commands?

### ISSUE THREAD

**Issue by hemfreitas11** [MatteZ02/discord-interactions#21]
When i try to create more than 5 commands i get the error
```
status: 429,
statusText: 'Too Many Requests',
```
```
data: {
      global: false,
      message: 'You are being rate limited.',
      retry_after: 19.877
    }
```
I don't know if the "retry_after" is in seconds or minutes, but it has been about 6 hours since i last tried this so pretty sure this cooldown should be over by now.

**Comment by Nicholaiii** [comment]
https://discord.com/developers/docs/topics/rate-limits#exceeding-a-rate-limit

<html><body>


retry_after | float | The number of seconds to wait before submitting another request.
-- | -- | --



</body>
</html>

Consider allowing some time between requests

**Comment by hemfreitas11** [comment]
After testing a little bit it seems you need to wait at least 4 seconds between the creation of each command if you have more than 5 commands. Thanks

**Comment by joelnedev** [comment]
yes, you should not be posting/putting commands on every startup as you only need to register each slash command once
