### ISSUE TITLE
The "interactionCreate" event is never fired.

### ISSUE THREAD

**Issue by deathlynocturnal** [MatteZ02/discord-interactions#22]
Hello!

I am using version: `1.2.1`.
I am using it with the normal discord client as well, see code here:

![image](https://user-images.githubusercontent.com/5339861/118462069-34dc6080-b6f6-11eb-917d-916547b496bb.png)

DSCC = your library.

When I run a command I just see: "This interaction failed." and I see no information in the output, I am using TypeScript (hence all the `(this.client as any)`.

The code inside of 'interactionCreate' never gets called.

To confirm, I have also used your fork of discord, and I have also made the change that the PR requests (which stops your fork from working completely).

**Comment by Nicholaiii** [comment]
You don't need to typecast to any, it's not good TS practise, you're just setting yourself up for failure. This lib even exports types. If you don't want to write an extended Discord.js Client interface, you should be able to just do something like this:
```ts
class Whatever {
  protected client: Client & { interactions: InteractionsClient }
}
```

(But seriously, that's just two lines less than writing an interface)

Did you try `'INTERACTION_CREATE'`? It's the event my bot consumes.

**Comment by richardhedges** [comment]
The `interactionCreate` event isn't firing for me either.

```javascript
const { token, id, guild } = require('./config.json')

const interactions = require('discord-slash-commands-client')
const Discord = require('discord.js')
const client = new Discord.Client()

client.interactions = new interactions.Client(token, id)

client.on('ready', () => {
	
    console.log('Bot Ready!')

    client.interactions.createCommand({
        name: 'ping',
        description: 'Ping test command'
    }, guild).then(console.log).catch(console.error)

})

client.on('interactionCreate', (interaction) => {
    console.log(interaction);
})

client.login(token)
```
