### ISSUE TITLE
getCommands() returns undefined

### ISSUE THREAD

**Issue by Alchete** [MatteZ02/discord-interactions#6]
Thanks, this library looks useful.  However, am I using it wrong?

My issue is that I somehow have two seemingly identical commands already active.  I registered these with previous, hand-code and can still access them in my server.  So, I was hoping to read back all my commands and delete the duplicate.  However, the readback gives me an undefined object.

```
const SlashCommands = require('discord-slash-commands-client')

bot.once('ready', () => {

    const interactions = new SlashCommands.Client(
        config.token, // bot token
        bot.user.id   // bot user id
        );

    // Get all current commands
    interactions.getCommands().then(console.log).catch(console.error);
```
Console output:
options must be of type object. Received: undefined

**Comment by MatteZ02** [comment]
Seems like there is an error in the code for that method. Ill take a look at it asap. Also i think theres a pr #5 that fixes this.

**Comment by Alchete** [comment]
Thanks MatteZ02, any luck so far?

**Comment by Nicholaiii** [comment]
> Thanks MatteZ02, any luck so far?

Using the patched version I can do this succesfully:
```ts
console.log(await client.interactions.getCommands())
```
I suspect if @MatteZ02 could publish the changes to npm, it'll work for you too.

**Comment by MatteZ02** [comment]
can you confirm that this works properly on latest?

**Comment by Alchete** [comment]
Thank you MatteZ02!  It works now for me.
