### ISSUE TITLE
Discord doesnt post "Member used Command with Bot" into text channel

### ISSUE THREAD

**Issue by SashaShtal** [MatteZ02/discord-interactions#7]
Using Discord API slash commands looks like this: 
![image](https://user-images.githubusercontent.com/51839212/103251628-7f00b780-498a-11eb-86da-9b6de295f5db.png)
But using discord-interactions bot doesnt post report message.
(I am using connecting method with discord.js integration)

**Comment by MatteZ02** [comment]
do you know if there was webhooks or gateway used to receive and send that notification/message?

**Comment by SashaShtal** [comment]
I dont know exactly.. this guy: https://www.youtube.com/watch?v=rqRkvk4Diiw used discord api to create slash commands. But writing so much code is very uncomfortable, so, i am using your API. It will be great, if u could create this notifications, and they could me turned on/off :з

**Comment by MatteZ02** [comment]
Ill take a look at it at some point. And see what he used to create those notifications.

**Comment by Nicholaiii** [comment]
This is likely because you are not using the interaction callback to respond. This library only handles creation of commands, not responding to them.

**Comment by SashaShtal** [comment]
It will be great, if @MatteZ02 create functions to respond to commands in the future. This moment it is the most comfortable library for my team :)

**Comment by MatteZ02** [comment]
I have plans to add support for using webhooks to get an interaction. So at that point this should be possible.

**Comment by DomeQdev** [comment]
@MatteZ02 any eta, when you release it?

**Comment by MatteZ02** [comment]
got no eta for that as of now

**Comment by joelnedev** [comment]
i think this has something to do with [Interaction Response Types](https://discord.com/developers/docs/interactions/slash-commands#interaction-response-interactionresponsetype). it would be helpful to choose what response type to use so for some commands it would eat the message and for others it would show it.

**Comment by Nicholaiii** [comment]
> i think this has something to do with [Interaction Response Types](https://discord.com/developers/docs/interactions/slash-commands#interaction-response-interactionresponsetype). it would be helpful to choose what response type to use so for some commands it would eat the message and for others it would show it.

https://discord.com/developers/docs/interactions/slash-commands#responding-to-an-interaction
@DomeQdev @SashaShtal @JuhJuhButts 
You can see on the docs how you're supposed to respond. This library doesn't handle responses currently.

**Comment by DomeQdev** [comment]
> > i think this has something to do with [Interaction Response Types](https://discord.com/developers/docs/interactions/slash-commands#interaction-response-interactionresponsetype). it would be helpful to choose what response type to use so for some commands it would eat the message and for others it would show it.
> 
> https://discord.com/developers/docs/interactions/slash-commands#responding-to-an-interaction
> @DomeQdev @SashaShtal @JuhJuhButts
> You can see on the docs how you're supposed to respond. This library doesn't handle responses currently.

but you can do it 🤔

**Comment by SashaShtal** [comment]
Ye, it will be nice, if MatteZ02 create ability to turn on/off info messages, as i wrote upper :з

**Comment by DomeQdev** [comment]
> Ye, it will be nice, if MatteZ02 create ability to turn on/off info messages, as i wrote upper :з

yeah it's good idea

**Comment by sevanescence** [comment]
> > > i think this has something to do with [Interaction Response Types](https://discord.com/developers/docs/interactions/slash-commands#interaction-response-interactionresponsetype). it would be helpful to choose what response type to use so for some commands it would eat the message and for others it would show it.
> > 
> > 
> > https://discord.com/developers/docs/interactions/slash-commands#responding-to-an-interaction
> > @DomeQdev @SashaShtal @JuhJuhButts
> > You can see on the docs how you're supposed to respond. This library doesn't handle responses currently.
> 
> but you can do it 🤔

Necro, but if I wanted to do it myself I wouldn't have used the library in the first place. (granted, now i have to)

**Comment by MatteZ02** [comment]
The discord.js fork now supports this.
